name: tensorflow
dependencies:
  - python=3.5.2
  # Required for Jupyter Notebooks.
  - jupyter

  - pip:
  
    - sklearn
    - matplotlib
    - keras-tqdm
    - numpy==1.13.1
    - keras==2.0.8
    - tensorflow==1.4.0
    - h5py==2.7.1
    - pandas==0.20.3